name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
author: zPedroo_
main: com.zpedroo.voltzevents.VoltzEvents
depend: [MultiEconomy]
softdepend: [PlaceholderAPI, Legendchat]
load: POSTWORLD