MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  command: eventos
  aliases: [events, event, evento]
  command-keys: # {event_cmd} {key}
    start: INICIAR
    cancel: CANCELAR
    set-pos1: SETPOS1
    set-pos2: SETPOS2
    set-arena: SETARENA
    set-win-region: SETWINREGION
    set-items: SETITEMS
    set-join: SETJOIN
    set-exit: SETEXIT
  admin-permission: events.admin
  host-event:
    permission: events.host
    cooldown: 1800 # segundos
  data-update-interval: 600 # segundos
  scoreboard-update-interval: 2 # ticks
  null-winner: 'Ninguém'
  disable-inventory-interaction: true # Essa opção é ignorada em eventos que o jogador entra com itens próprios
  disable-item-pickup: true # Essa opção é ignorada em eventos que o jogador entra com itens próprios
  disable-item-drop: true # Essa opção é ignorada em eventos que o jogador entra com itens próprios
  disable-block-place: true
  disable-block-break: true
  time-formatter: 'mm:ss'
  currency-separator: ' &7+ '
  cancel-action-key: 'CANCELAR'

Messages:
  blacklisted-command: '&cVocê não pode executar esse comando durante o evento!'
  already-started: '&cEsse evento já está ocorrendo!'
  not-started: '&cEsse evento não está ocorrendo!'
  already-participating: '&cVocê já está participando de um evento!'
  invalid-location: '&cEsse evento não possui todas localizações definidas!'
  invalid-position: '&cVocê ainda não definiu todas posições!'
  invalid-checkpoint: '&cVocê ainda não possui nenhum checkpoint!'
  invalid-rewards: '&cVocê precisa adicionar pelo menos uma recompensa!'
  invalid-event: '&cVocê precisa escolher um evento!'
  invalid-amount: '&cA quantia informada é inválida!'
  minimum-value: '&cA quantia precisa ser maior que {minimum}!'
  insufficient-currency: '&cVocê não pode pagar todas essas recompensas!'
  position-set: '&7Posição &f{pos} &7definida com sucesso!'
  add-currency:
    - '&7Digite no chat quanto você deseja adicionar!'
    - ''
    - ' &8▶ &7Moeda: {currency}'
    - ' &8▶ &7Quantia atual: {currency_amount}'
    - ' &8▶ &7Valor mínimo: {currency_min_amount}'
    - ''
  remove-currency:
    - '&7Digite no chat quanto você deseja remover!'
    - ''
    - ' &8▶ &7Moeda: {currency}'
    - ' &8▶ &7Quantia atual: {currency_amount}'
    - ' &8▶ &7Valor mínimo: {currency_min_amount}'
    - ''

Countdown-Titles:
  10:
    title: '&a10'
    subtitle: ''
  5:
    title: '&e5'
    subtitle: ''
  4:
    title: '&e4'
    subtitle: ''
  3:
    title: '&c3'
    subtitle: ''
  2:
    title: '&c2'
    subtitle: ''
  1:
    title: '&c1'
    subtitle: ''

Special-Items:
  visibility:
    action: SWITCH_VISIBILITY
    default-item:
      type: INK_SACK
      data: 10
      name: '&fJogadores: &a&lON'
    secondary-item:
      type: INK_SACK
      data: 8
      name: '&fJogadores: &c&lOFF'
  checkpoint:
    action: CHECKPOINT
    type: WATCH
    name: '&aCheckpoint'
  leave:
    action: LEAVE
    type: DARK_OAK_DOOR_ITEM
    name: '&cSair'

Set-Region-Items:
  1:
    slot: 0
    action: POS
    type: BLAZE_ROD
    name: '&aDefinir Posições'
    lore:
      - '&7Botão &fesquerdo&7: &7Pos &f1'
      - '&7Botão &fdireito&7: &7Pos &f2'
  2:
    slot: 7
    action: CONFIRM
    type: SKULL_ITEM
    owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTllNGJkY2YxNzJkNWRjNzdjMmJkNGUzN2FkOTg1Mzk5YTlmMmNkZWJmNzI0NjM5MjllYTRiNjY2ZWY2ZjgwIn19fQ==
    name: '&aConfirmar'
  3:
    slot: 8
    action: CANCEL
    type: SKULL_ITEM
    owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZkZTNiZmNlMmQ4Y2I3MjRkZTg1NTZlNWVjMjFiN2YxNWY1ODQ2ODRhYjc4NTIxNGFkZDE2NGJlNzYyNGIifX19
    name: '&cCancelar'

Time-Formatter:
  second: 'segundo'
  seconds: 'segundos'
  minute: 'minuto'
  minutes: 'minutos'
  hour: 'hora'
  hours: 'horas'
  day: 'dia'
  days: 'dias'
  now: 'Agora'